### PR TITLE
Update Create form schema to use author

### PR DESCRIPTION
**Pull request by amoeba**
Updates the form to match changes in https://github.com/codemeta/codemeta/issues/223

### CODE REVIEW

**Comment by cboettig** [comment]
Thanks @amoeba !  But just a note, I think we're planning to drop this form entirely in favor of the one contributed by Software Heritage team at https://github.com/codemeta/codemeta-generator (oh wait, it's not been migrated yet, so it's still at https://forge.softwareheritage.org/source/codemeta-generator/)  

I think that one is also pure client-side javascript but havent had a chance to dig in here...

**Comment by amoeba** [comment]
Hey @cboettig. That sounds great. I'm okay with merging or not merging this so feel free to close.

**Comment by mbjones** [comment]
@amoeba We switched the editor over to use the new generator created by Software Heritage.  Is there anything in this PR that we should try to keep, or can we close it?

**Comment by mbjones** [comment]
NM, just saw your message to 'feel free to close it", so that's what I am doing.  Reopen if we missed something.

**Pull request closed without merging**
