### PR TITLE
Fix two links in developer-guide.md

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by mbjones** [comment]
LGTM. Thanks.

**Comment by mbjones** [comment]
@cboettig is the codemeta site deploy automated now, or do we have to build and push it up?

**Comment by cboettig** [comment]
@zuphilip Thanks!  

@mbjones it's manual, we could automate it via CI of course.  

I was wondering if we should consider getting a dedicated URL for codemeta, e.g. `codemeta-project.org` or something, rather than the current GitHub URL?  Among other things, then we could run the hosting from netlify, which could automate the hugo builds with less fussing than pushing back to GH from CI.  Thoughts?

**Comment by mbjones** [comment]
We could get a domain.  But then its just one more to pay for and maintain.  Netlify would be nice.  I should be given stock for all the domains I pay for on namecheap.  Its hard for me to get the university to pay that stuff, and just chews up time.  But despite my sniping I think its a good idea.

**Pull request merged**
