### PR TITLE
Adds tributors and cff-converter to tools list

### PR DESCRIPTION
**Pull request by vuillaut**
I am not involved  in the development of these tools but I would have liked to discover them when I discovered codemeta, hence the request to add them to the list.

### CODE REVIEW

**Comment by vuillaut** [comment]
I convert to draft, it seems the `cff-converter` does not do a very good job :-/

**Comment by moranegg** [comment]
Hello,

Thank you for the PR. Sorry about the delayed response.
At the moment there is a conflict, can you check that?

Best,

**Comment by vuillaut** [comment]
> Hello,
> 
> Thank you for the PR. Sorry about the delayed response. At the moment there is a conflict, can you check that?
> 
> Best,

Hi.
Done.

**Comment by moranegg** [comment]
Thank you for your quick fix.

**Pull request merged**
